apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  labels:
    app: content-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: whatthehackmsft/content-api:v2
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 3001
